version: "3.9"
services:
#  db:
#      image: postgres:alpine
#      ports:
#        - "5432:5432"
#      environment:
#        - POSTGRES_USER=${DB_USERNAME}
#        - POSTGRES_PASSWORD=${DB_PASSWORD}
#        - POSTGRES_DB=${DB_DATABAS}
  web:
    build: .
    ports:
      - "5000:5000"
#    depends_on:
#      - db